%  Leer los archivos de las bases de datos
datos_pacientes = readtable('data.csv');
datos_pacientes_1 = readtable('breast cancer.csv');
datos_pacientes_2 = readtable('bcsc_risk_factors_summarized1_092020.csv');
datos_pacientes_3 = readtable('bcsc_risk_factors_summarized2_092020.csv');
datos_pacientes_4 = readtable('bcsc_risk_factors_summarized3_092020.csv');

%  Encuesta para recopilar datos demográficos
disp('Por favor, responde las siguientes preguntas:');
edad = input('¿Cuál es tu edad? ');
lesiones = input('¿Presencia de lesiones benignas y/o malignas? (Si/No)  (cuáles y dónde) ', 's');
Fumar = input('¿Fuma o fumó alguna vez en su vida? (Si/No) ');
alcohol = input('¿Ingiere bebidas alcohólicas? Si_ No_ ');
grasa1 = input('¿Consume grasa animal?Si_ No_ ');
grasa2 = input('¿Con qué frecuencia consume grasa animal? Nunca: _ Ocasionalmente: _ Frecuentemente:_ ');
estatura = input('¿Cul es su Estatura(cm)?');
IMC = input('¿Cual es su IMC? ');
anticonceptivos = input(' ¿Ha utilizado anticonceptivos hormonales alguna vez en su vida? (Si/No)  ');
edad_menstruacion = input(' Edad de la primera menstruación : ');
parto = input(' ¿Ha tenido partos? (Si/No)  ');
partos = input(' Número de partos: ');
lactancia = input('﻿﻿ ﻿﻿Dio lactancia materna:(Si/No)  ');

n = 1; % Número de iteraciones del bucle for

for i = 1:n
    % Coloca aquí el código que deseas ejecutar en cada iteración
    parto = input(' ¿Ha tenido partos? (Si/No): ');
    % Pregunta al usuario si desea continuar
    respuesta = input('¿Desea continuar? (si/no): ', 's');
    partos = input(' Número de partos: ');
    lactancia = input('﻿﻿ ﻿﻿Dio lactancia materna: Si_No_ ');
    % Verifica la respuesta
    if strcmpi(respuesta, 'no')
        break; % Sale del bucle si la respuesta es "no"
    end
end

Edad_menopausia = input('﻿﻿Edad de la menopausia: ');
Antecedentes = input('﻿﻿﻿﻿Antecedentes patológicos familiares de cáncer de mama?Si_No_? ﻿﻿Sin antecedentes_ ﻿﻿Con antecedentes_:');
birad1 = input('﻿﻿ Presentó prueba de birads ');
Birad = input('﻿﻿ ¿Cual fue su prueba de Birads');
peso = input('﻿﻿ Edad del primer parto: ');


paciente_nuevo = table(edad,lesiones,fumar,alcohol,grasa1,grasa2,estatura,IMC,anticonceptivos,edad_menstruacion,parto,partos,lactancia, Edad_menopausia,Antecedentes,birad1,Birad,peso ); % Crear tabla con las respuestas de la encuesta
% Filtrar pacientes en la base de datos que coincidan con la edad y género del paciente nuevo
pacientes_coincidentes = datos_pacientes(datos_pacientes.Edad == edad & strcmp(datos_pacientes.lesiones, lesiones) & strcmp(datos_pacientes.fumar, fumar) & strcmp(datos_pacientes.alcohol, alcohol) & strcmp(datos_pacientes.grasa1, grasa1) & strcmp(datos_pacientes.grasa2, grasa2) & strcmp(datos_pacientes.estatura, estatura) & strcmp(datos_pacientes.IMC, IMC) & strcmp(datos_pacientes.anticonceptivos, anticonceptivos) & strcmp(datos_pacientes.edad_menstruacion, edad_menstruacion) & strcmp(datos_pacientes.parto, parto) & strcmp(datos_pacientes.partos, partos)& strcmp(datos_pacientes.lactancia, lactancia) & strcmp(datos_pacientes.Edad_menopausia, Edad_menopausia)& strcmp(datos_pacientes.antecedentes, antecedentes)& strcmp(datos_pacientes.birad1, birad1)& strcmp(datos_pacientes.Birad, Birad)& strcmp(datos_pacientes.peso, peso);
pacientes_coincidentes_1 = datos_pacientes_1(datos_pacientes_1.Edad == edad & strcmp(datos_pacientes_1.lesiones, lesiones) & strcmp(datos_pacientes_1.fumar, fumar) & strcmp(datos_pacientes_1.alcohol, alcohol) & strcmp(datos_pacientes_1.grasa1, grasa1) & strcmp(datos_pacientes_1.grasa2, grasa2) & strcmp(datos_pacientes_1.estatura, estatura) & strcmp(datos_pacientes_1.IMC, IMC) & strcmp(datos_pacientes_1.anticonceptivos, anticonceptivos) & strcmp(datos_pacientes_1.edad_menstruacion, edad_menstruacion) & strcmp(datos_pacientes_1.parto, parto) & strcmp(datos_pacientes_1.partos, partos)& strcmp(datos_pacientes_1.lactancia, lactancia) & strcmp(datos_pacientes_1.Edad_menopausia, Edad_menopausia)& strcmp(datos_pacientes_1.antecedentes, antecedentes)& strcmp(datos_pacientes_1.birad1, birad1)& strcmp(datos_pacientes.Birad, Birad)& strcmp(datos_pacientes.peso, peso);
pacientes_coincidentes_2 = datos_pacientes_2(datos_pacientes_2.Edad == edad & strcmp(datos_pacientes_2.lesiones, lesiones) & strcmp(datos_pacientes_2.fumar, fumar) & strcmp(datos_pacientes_2.alcohol, alcohol) & strcmp(datos_pacientes_2.grasa1, grasa1) & strcmp(datos_pacientes_2.grasa2, grasa2) & strcmp(datos_pacientes_2.estatura, estatura) & strcmp(datos_pacientes_2.IMC, IMC) & strcmp(datos_pacientes_2.anticonceptivos, anticonceptivos) & strcmp(datos_pacientes_2.edad_menstruacion, edad_menstruacion) & strcmp(datos_pacientes_2.parto, parto) & strcmp(datos_pacientes_2.partos, partos)& strcmp(datos_pacientes_2.lactancia, lactancia) & strcmp(datos_pacientes_2.Edad_menopausia, Edad_menopausia)& strcmp(datos_pacientes_2.antecedentes, antecedentes)& strcmp(datos_pacientes_2.birad1, birad1)& strcmp(datos_pacientes.Birad, Birad)& strcmp(datos_pacientes.peso, peso);
pacientes_coincidentes_3 = datos_pacientes_3(datos_pacientes_3.Edad == edad & strcmp(datos_pacientes_3.lesiones, lesiones) & strcmp(datos_pacientes_3.fumar, fumar) & strcmp(datos_pacientes_3.alcohol, alcohol) & strcmp(datos_pacientes_3.grasa1, grasa1) & strcmp(datos_pacientes_3.grasa2, grasa2) & strcmp(datos_pacientes_3.estatura, estatura) & strcmp(datos_pacientes_3.IMC, IMC) & strcmp(datos_pacientes_3.anticonceptivos, anticonceptivos) & strcmp(datos_pacientes_3.edad_menstruacion, edad_menstruacion) & strcmp(datos_pacientes_3.parto, parto) & strcmp(datos_pacientes_3.partos, partos)& strcmp(datos_pacientes_3.lactancia, lactancia) & strcmp(datos_pacientes_3.Edad_menopausia, Edad_menopausia)& strcmp(datos_pacientes_3.antecedentes, antecedentes)& strcmp(datos_pacientes_3.birad1, birad1)& strcmp(datos_pacientes.Birad, Birad)& strcmp(datos_pacientes.peso, peso);
pacientes_coincidentes_4 = datos_pacientes_4(datos_pacientes_4.Edad == edad & strcmp(datos_pacientes_4.lesiones, lesiones) & strcmp(datos_pacientes_4.fumar, fumar) & strcmp(datos_pacientes_4.alcohol, alcohol) & strcmp(datos_pacientes_4.grasa1, grasa1) & strcmp(datos_pacientes_4.grasa2, grasa2) & strcmp(datos_pacientes_4.estatura, estatura) & strcmp(datos_pacientes_4.IMC, IMC) & strcmp(datos_pacientes_4.anticonceptivos, anticonceptivos) & strcmp(datos_pacientes_4.edad_menstruacion, edad_menstruacion) & strcmp(datos_pacientes_4.parto, parto) & strcmp(datos_pacientes_4.partos, partos)& strcmp(datos_pacientes_4.lactancia, lactancia) & strcmp(datos_pacientes_4.Edad_menopausia, Edad_menopausia)& strcmp(datos_pacientes_4.antecedentes, antecedentes)& strcmp(datos_pacientes_4.birad1, birad1)& strcmp(datos_pacientes.Birad, Birad)& strcmp(datos_pacientes.peso, peso);

% Dictaminar la probabilidad de tener cáncer de mama
if height(pacientes_coincidentes) > 12
    disp('Hay una alta probabilidad de tener cáncer de mama.');
else
    disp('No hay una alta probabilidad de tener cáncer de mama.');
end
